export class StringResource {

		language=[
				{'language':"Hindi"},
				{'language':"Marathi"},
				{'language':"Assamese"},
				{'language':"Bengali"},
				{'language':"Dogri"},
				{'language':"Gujarati"},
				{'language':" Punjabi"},
				{'language':"Bodo"},
				{'language':"Kannada"},
				{'language':"Kashmiri"},
				{'language':"Urdu"},
				{'language':"Telegu"},
				{'language':"Konkani"},
				{'language':"Malayalam"},
				{'language':"Manipuri or Meithei"},
				{'language':"English"},
				{'language':"Nepali"},
				{'language':"Oriya"},
				{'language':"Sanskrit"},
				{'language':"Santali"},
				{'language':"Sindhi"},
				{'language':"Tamil"}
		      ]
	      stateList= [
				 {stateName: "Andhra Pradesh"},
				 {stateName: "Arunachal Pradesh"},
				 {stateName: "Assam"},
				 {stateName: "Bihar"},
				 {stateName: "Chhattisgarh"},
				 {stateName: "Goa"},
				 {stateName: "Gujarat"},
				 {stateName: "Haryana"},
				 {stateName: "Himachal Pradesh"},
				 {stateName: "Jammu and Kashmir"},
				 {stateName: "Jharkhand"},
				 {stateName: "Karnataka"},
				 {stateName: "Kerala"},
				 {stateName: "Madhya Pradesh"},
				 {stateName: "Maharashtra"},
				 {stateName: "Manipur"},
				 {stateName: "Meghalaya"},
				 {stateName: "Mizoram"},
				 {stateName: "Nagaland"},
				 {stateName: "Odisha"},
				 {stateName: "Punjab"},
				 {stateName: "Rajasthan"},
				 {stateName: "Sikkim"},
				 {stateName: "Tamil Nadu"},
				 {stateName: "Telangana"},
				 {stateName: "Tripura"},
				 {stateName: "Uttar Pradesh"},
				 {stateName: "Uttarakhand"},
				 {stateName: "West Bengal"},
				 {stateName: "Andaman and Nicobar Islands"},
				 {stateName: "Chandigarh"},
				 {stateName: "Dadra and Nagar Haveli"},
				 {stateName: "Daman and Diu"},
				 {stateName: "National Capital Territory of Delhi"},
				 {stateName: "Lakshadweep"},
				 {stateName: "Pondicherry "}
				];
}