export class StateResource {
	state=[
		{
         name:'JAMMU & KASHMIR',
         dist:[
	         {
	         	name:'Kupwara',
	         	block:[
		         	{
                      name:'Kupwara'
		         	},
		         	{
                      name:'Handwara'
		         	},
		         	{
                      name:'Karnah'
		         	}
	         	]
	         },
	         {
                name:'Badgam',
	         	block:[
		         	{
                      name:'Badgam'
		         	},
		         	{
                      name:'Khag'
		         	},
		         	{
                      name:'Beerwah'
		         	},
		         	{
                      name:'Khansahib'
		         	},
		         	{
                      name:'Chadoora'
		         	},
		         	{
                      name:'Charar- E- Shrief'
		         	}
	         	]
	         },
	         {
                name:'Leh(Ladakh)',
	         	block:[
		         	{
                      name:'Leh(Ladakh)'
		         	},
		         	{
                      name:'Nubra'
		         	},
		         	{
                      name:'Khalsi'
		         	}
	         	]
	         },
	          {
                name:'Kargil',
	         	block:[
		         	{
                      name:'Kargil'
		         	},
		         	{
                      name:'Sanku'
		         	},
		         	{
                      name:'Zanskar'
		         	}
	         	]
	         },
	          {
                name:'Punch',
	         	block:[
		         	{
                      name:'Punch'
		         	},
		         	{
                      name:'Haveli'
		         	},
		         	{
                      name:'Mandi'
		         	},
		         	{
                      name:'Mendhar'
		         	},
		         	{
                      name:'Surankote'
		         	}
	         	]
	         },
	          {
                name:'Rajouri',
	         	block:[
		         	{
                      name:'Rajouri'
		         	},
		         	{
                      name:'Thanamandi'
		         	},
		         	{
                      name:'Darhal'
		         	},
		         	{
                      name:'Rajauri'
		         	},
		         	{
                      name:'Budhal'
		         	},
		         	{
                      name:'Kalakote'
		         	},
		         	{
                      name:'Nowshehra'
		         	},
		         	{
                      name:'Sunderbani'
		         	}
	         	]
	         },
	         {
                name:'Kathua',
	         	block:[
		         	{
                      name:'Kathua'
		         	},
		         	{
                      name:'Billawar'
		         	},
		         	{
                      name:'Bashohli'
		         	},
		         	{
                      name:'Bani'
		         	},
		         	{
                      name:'Kathua'
		         	},
		         	{
                      name:'Hiranagar'
		         	}
	         	]
	         },
	         {
                name:'Baramula',
	         	block:[
		         	{
                      name:'Baramula'
		         	},
		         	{
                      name:'Sopore'
		         	},
		         	{
                      name:'Sopore'
		         	},
		         	{
                      name:'Rafiabad'
		         	},
		         	{
                      name:'Pattan'
		         	},
		         	{
                      name:'Baramulla'
		         	},
		         	{
                      name:'Kreeri'
		         	},
		         	{
                      name:'Uri'
		         	},
		         	{
                      name:'Boniyar'
		         	},
		         	{
                      name:'Tangmarg'
		         	}
	         	]
	         },
	         {
                name:'Bandipore',
	         	block:[
		         	{
                      name:'Bandipore'
		         	},
		         	{
                      name:'Gurez'
		         	},
		         	{
                      name:'Bandipora'
		         	},
		         	{
                      name:'Sonawari'
		         	}
	         	]
	         },
	         {
                name:'Srinagar',
	         	block:[
		         	{
                      name:'Srinagar'
		         	},
		         	{
                      name:'Srinagar (North)'
		         	},
		         	{
                      name:'Srinagar (South)'
		         	}
	         	]
	         },
	         {
                name:'Srinagar',
	         	block:[
		         	{
                      name:'Srinagar'
		         	},
		         	{
                      name:'Srinagar (North)'
		         	},
		         	{
                      name:'Srinagar (South)'
		         	}
	         	]
	         },
	         {
                name:'Ganderbal',
	         	block:[
		         	{
                      name:'Ganderbal'
		         	},
		         	{
                      name:'Lar'
		         	},
		         	{
                      name:'Kangan'
		         	},
		         	{
                      name:'Ganderbal'
		         	}
	         	]
	         },
	         {
                name:'Pulwama',
	         	block:[
		         	{
                      name:'Pulwama'
		         	},
		         	{
                      name:'Pampore'
		         	},
		         	{
                      name:'Awantipora'
		         	},
		         	{
                      name:'Tral'
		         	}
	         	]
	         },
	         {
                name:'Shupiyan',
	         	block:[
		         	{
                      name:'Shupiyan'
		         	},
		         	{
                      name:'Shopian'
		         	}
	         	]
	         },
	         {
                name:'Anantnag',
	         	block:[
		         	{
                      name:'Anantnag'
		         	},
		         	{
                      name:'Pahalgam'
		         	},
		         	{
                      name:'Bijbehara'
		         	},
		         	{
                      name:'Anantnag'
		         	},
		         	{
                      name:'Shangus'
		         	},
		         	{
                      name:'Kokernag'
		         	},
		         	{
                      name:'Dooru'
		         	}
	         	]
	         },
	         {
                name:'Kulgam',
	         	block:[
		         	{
                      name:'Kulgam'
		         	},
		         	{
                      name:'Devsar'
		         	},
		         	{
                      name:'Damhal Hanjipora'
		         	}
	         	]
	         },
	         {
                name:'Doda',
	         	block:[
		         	{
                      name:'Doda'
		         	},
		         	{
                      name:'Thathri'
		         	},
		         	{
                      name:'Gandoh'
		         	},
		         	{
                      name:'Bhaderwah'
		         	}
	         	]
	         },
	         {
                name:'Ramban',
	         	block:[
		         	{
                      name:'Ramban'
		         	},
		         	{
                      name:'Banihal'
		         	}
	         	]
	         },
	         {
                name:'Kishtwar',
	         	block:[
		         	{
                      name:'Kishtwar'
		         	},
		         	{
                      name:'Marwah'
		         	},
		         	{
                      name:'Chhatroo'
		         	},
		         	{
                      name:'Atholi (Paddar)'
		         	}
	         	]
	         },
	         {
                name:'Udhampur',
	         	block:[
		         	{
                      name:'Udhampur'
		         	},
		         	{
                      name:'Chenani'
		         	},
		         	{
                      name:'Ramnagar'
		         	},
		         	{
                      name:'Majalta'
		         	}
	         	]
	         },
	         {
                name:'Reasi',
	         	block:[
		         	{
                      name:'Reasi'
		         	},
		         	{
                      name:'Gool-Gulabgarh'
		         	}
	         	]
	         },
	         {
                name:'Jammu',
	         	block:[
		         	{
                      name:'Jammu'
		         	},
		         	{
                      name:'Akhnoor'
		         	},
		         	{
                      name:'Ranbir Singh Pora'
		         	},
		         	{
                      name:'Bishnah'
                    }
	         	]
	         },
	         {
                name:'Samba',
	         	block:[
		         	{
                      name:'Samba'
		         	}
	         	]
	         }
         ]
		},{
		 name:'HIMACHAL PRADESH',
         dist:[
	         {
	         	name:'Chamba',
	         	block:[
		         	{
                      name:'Chamba'
		         	},
		         	{
                      name:'Pangi'
		         	},
		         	{
                      name:'Chaurah'
		         	},
		         	{
                      name:'Saluni'
		         	},
		         	{
                      name:'Bhalai'
		         	},
		         	{
                      name:'Dalhousie'
		         	},
		         	{
                      name:'Bhattiyat'
		         	},
		         	{
                      name:'Sihunta'
		         	},
		         	{
                      name:'Holi'
		         	},
		         	{
                      name:'Brahmaur'
		         	}
	         	]
	         },
	          {
	         	name:'Kangra',
	         	block:[
		         	{
                      name:'Kangra'
		         	},
		         	{
                      name:'Nurpur'
		         	},
		         	{
                      name:'Indora'
		         	},
		         	{
                      name:'Fatehpur'
		         	},
		         	{
                      name:'Jawali'
		         	},
		         	{
                      name:'Harchakian'
		         	},
		         	{
                      name:'Shahpur'
		         	},
		         	{
                      name:'Dharmsala'
		         	},
		         	{
                      name:'Nagrota Bagwan'
		         	},
		         	{
                      name:'Baroh'
		         	},
		         	{
                      name:'Dera Gopipur'
		         	},
		         	{
                      name:'Jawalamukhi'
		         	},
		         	{
                      name:'Jaswan'
		         	},
		         	{
                      name:'Rakkar'
		         	},
		         	{
                      name:'Khundian'
		         	},
		         	{
                      name:'Thural'
		         	},
		         	{
                      name:'Dhira'
		         	},
		         	{
                      name:'Jaisinghpur'
		         	},
		         	{
                      name:'Palampur'
		         	},
		         	{
                      name:'Baijnath'
		         	},
		         	{
                      name:'Multhan'
		         	}
	         	]
	         },
	          {
	         	name:'Lahul & Spiti',
	         	block:[
		         	{
                      name:'Lahul & Spiti'
		         	},
		         	{
                      name:'Nurpur'
		         	},
		         	{
                      name:'Lahul'
		         	},
		         	{
                      name:'Spiti'
		         	}
	         	]
	         },
	          {
	         	name:'Kullu',
	         	block:[
		         	{
                      name:'Kullu'
		         	},
		         	{
                      name:'Manali'
		         	},
		         	{
                      name:'Sainj'
		         	},
		         	{
                      name:'Banjar'
		         	},
		         	{
                      name:'Ani'
		         	},
		         	{
                      name:'Nermand'
		         	}
	         	]
	         },
	          {
	         	name:'Mandi',
	         	block:[
		         	{
                      name:'Mandi'
		         	},
		         	{
                      name:'Padhar'
		         	},
		         	{
                      name:'Jogindarnagar'
		         	},
		         	{
                      name:'Lad Bharol'
		         	},
		         	{
                      name:'Sandhol'
		         	},
		         	{
                      name:'Dharmpur'
		         	},
		         	{
                      name:'Kotli'
		         	},
		         	{
                      name:'Sarkaghat'
		         	},
		         	{
                      name:'Bhadrota'
		         	},
		         	{
                      name:'Baldwara'
		         	},
		         	{
                      name:'Sundarnagar'
		         	},
		         	{
                      name:'Aut'
		         	},
		         	{
                      name:'Bali Chowki'
		         	},
		         	{
                      name:'Thunag'
		         	},
		         	{
                      name:'Chachyot'
		         	},
		         	{
                      name:'Nihri'
		         	},
		         	{
                      name:'Karsog'
		         	}
	         	]
	         },
	          {
	         	name:'Hamirpur',
	         	block:[
		         	{
                      name:'Hamirpur'
		         	},
		         	{
                      name:'Tira Sujanpur'
		         	},
		         	{
                      name:'Nadaun'
		         	},
		         	{
                      name:'Galore'
		         	},
		         	{
                      name:'Barsar'
		         	},
		         	{
                      name:'Dhatwal'
		         	},
		         	{
                      name:'Bhoranj'
		         	}
	         	]
	         },
	          {
	         	name:'Una',
	         	block:[
		         	{
                      name:'Una'
		         	},
		         	{
                      name:'Bharwain'
		         	},
		         	{
                      name:'Amb'
		         	},
		         	{
                      name:'Bangana'
		         	},
		         	{
                      name:'Haroli'
		         	}
	         	]
	         },
	          {
	         	name:'Bilaspur',
	         	block:[
		         	{
                      name:'Bilaspur'
		         	},
		         	{
                      name:'Ghumarwin'
		         	},
		         	{
                      name:'Bharari'
		         	},
		         	{
                      name:'Jhanduta'
		         	},
		         	{
                      name:'Naina Devi'
		         	},
		         	{
                      name:'Bilaspur Sadar'
		         	},
		         	{
                      name:'Namhol'
		         	}
	         	]
	         },
	          {
	         	name:'Solan',
	         	block:[
		         	{
                      name:'Solan'
		         	},
		         	{
                      name:'Arki'
		         	},
		         	{
                      name:'Darlaghat'
		         	},
		         	{
                      name:'Ramshahr'
		         	},
		         	{
                      name:'Nalagarh'
		         	},
		         	{
                      name:'Baddi'
		         	},
		         	{
                      name:'Krishangarh'
		         	},
		         	{
                      name:'Kasauli'
		         	},
		         	{
                      name:'Kandaghat'
		         	}
	         	]
	         },
	          {
	         	name:'Sirmaur',
	         	block:[
		         	{
                      name:'Sirmaur'
		         	},
		         	{
                      name:'Rajgarh'
		         	},
		         	{
                      name:'Nohra'
		         	},
		         	{
                      name:'Pachhad'
		         	},
		         	{
                      name:'Renuka'
		         	},
		         	{
                      name:'Dadahu'
		         	},
		         	{
                      name:'Nahan'
		         	},
		         	{
                      name:'Paonta Sahib'
		         	},
		         	{
                      name:'Kamrau'
		         	},
		         	{
                      name:'Shalai'
		         	},
		         	{
                      name:'Ronhat'
		         	},
		         	{
                      name:'Ronhat'
		         	}
	         	]
	         },
	         {
	         	name:'Shimla',
	         	block:[
		         	{
                      name:'Shimla'
		         	},
		         	{
                      name:'Rampur'
		         	},
		         	{
                      name:'Nankhari'
		         	},
		         	{
                      name:'Kumharsain'
		         	},
		         	{
                      name:'Seoni'
		         	},
		         	{
                      name:'Shimla( Rural )'
		         	},
		         	{
                      name:'Junga'
		         	},
		         	{
                      name:'Theog'
		         	},
		         	{
                      name:'Chaupal'
		         	},
		         	{
                      name:'Cheta'
		         	},
		         	{
                      name:'Nerua'
		         	},
		         	{
                      name:'Jubbal'
		         	},
		         	{
                      name:'Kotkhai'
		         	},
		         	{
                      name:'Tikar'
		         	},
		         	{
                      name:'Rohru'
		         	},
		         	{
                      name:'Chirgaon'
		         	},
		         	{
                      name:'Dodra Kwar'
		         	}
	         	]
	         },
	         {
	         	name:'Kinnaur',
	         	block:[
		         	{
                      name:'Kinnaur'
		         	},
		         	{
                      name:'Hangrang'
		         	},
		         	{
                      name:'Poo'
		         	},
		         	{
                      name:'Morang'
		         	},
		         	{
                      name:'Kalpa'
		         	},
		         	{
                      name:'Nichar'
		         	},
		         	{
                      name:'Sangla'
		         	}
	         	]
	         }
	       ]
		},{
		 name:'PUNJAB',
         dist:[
	         {
	         	name:'Gurdaspur',
	         	block:[
		         	{
                      name:'Gurdaspur'
		         	},
		         	{
                      name:'Dhar Kalan'
		         	},
		         	{
                      name:'Pathankot'
		         	},
		         	{
                      name:'Batala'
		         	},
		         	{
                      name:'Dera Baba Nanak  '
		         	}
	         	]
	         },
	         {
	         	name:'Kapurthala',
	         	block:[
		         	{
                      name:'Kapurthala'
		         	},
		         	{
                      name:'Bhulath'
		         	},
		         	{
                      name:'Sultanpur Lodhi'
		         	},
		         	{
                      name:'Phagwara'
		         	}
	         	]
	         },
	         {
	         	name:'Jalandhar',
	         	block:[
		         	{
                      name:'Jalandhar'
		         	},
		         	{
                      name:'Shahkot'
		         	},
		         	{
                      name:'Phillaur'
		         	},
		         	{
                      name:'Jalandhar - I'
		         	},
		         	{
                      name:'Jalandhar - II'
		         	}
	         	]
	         },
	         {
	         	name:'Hoshiarpur',
	         	block:[
		         	{
                      name:'Hoshiarpur'
		         	},
		         	{
                      name:'Dasua'
		         	},
		         	{
                      name:'Mukerian'
		         	},
		         	{
                      name:'Garhshankar'
		         	}
	         	]
	         },
	         {
	         	name:'Shahid Bhagat Singh Nagar',
	         	block:[
		         	{
                      name:'Shahid Bhagat Singh Nagar'
		         	},
		         	{
                      name:'Nawanshahr'
		         	},
		         	{
                      name:'Balachaur'
		         	}
	         	]
	         },
	         {
	         	name:'Fatehgarh Sahib',
	         	block:[
		         	{
                      name:'Fatehgarh Sahib'
		         	},
		         	{
                      name:'Bassi Pathana'
		         	},
		         	{
                      name:'Amloh'
		         	},
		         	{
                      name:'Khamanon'
		         	}
	         	]
	         },
	         {
	         	name:'Ludhiana',
	         	block:[
		         	{
                      name:'Ludhiana'
		         	},
		         	{
                      name:'Samrala'
		         	},
		         	{
                      name:'Khanna'
		         	},
		         	{
                      name:'Payal'
		         	},
		         	{
                      name:'Ludhiana (East)'
		         	},
		         	{
                      name:'Ludhiana (West)'
		         	},
		         	{
                      name:'Raikot'
		         	},
		         	{
                      name:'Jagraon'
		         	}
	         	]
	         },
	         {
	         	name:'Moga',
	         	block:[
		         	{
                      name:'Moga'
		         	},
		         	{
                      name:'Nihal Singhwala'
		         	},
		         	{
                      name:'Bagha Purana'
		         	}
	         	]
	         },{
	         	name:'Firozpur',
	         	block:[
		         	{
                      name:'Firozpur'
		         	},
		         	{
                      name:'Zira'
		         	},
		         	{
                      name:'Jalalabad '
		         	}
	         	]
	         },{
	         	name:'Firozpur',
	         	block:[
		         	{
                      name:'Firozpur'
		         	},
		         	{
                      name:'Zira'
		         	},
		         	{
                      name:'Jalalabad'
		         	},
		         	{
                      name:'Fazilka'
		         	},
		         	{
                      name:'Abohar'
		         	}
	         	]
	         },{
	         	name:'Faridkot',
	         	block:[
		         	{
                      name:'Faridkot'
		         	},
		         	{
                      name:'Jaitu'
		         	}
	         	]
	         },{
	         	name:'Bathinda',
	         	block:[
		         	{
                      name:'Bathinda'
		         	},
		         	{
                      name:'Rampura Phul'
		         	},
		         	{
                      name:'Talwandi Sabo'
		         	},
		         	{
                      name:'Talwandi Sabo'
		         	}
	         	]
	         },{
	         	name:'Mansa',
	         	block:[
		         	{
                      name:'Mansa'
		         	},
		         	{
                      name:'Sardulgarh'
		         	},
		         	{
                      name:'Budhlada'
		         	}
	         	]
	         },
	         {
	         	name:'Patiala',
	         	block:[
		         	{
                      name:'Patiala'
		         	},
		         	{
                      name:'Samana'
		         	},
		         	{
                      name:'Patran'
		         	},
		         	{
                      name:'Nabha'
		         	},
		         	{
		         		name:'Rajpura'
		         	}
	         	]
	         },
	         {
	         	name:'Amritsar',
	         	block:[
		         	{
                      name:'Amritsar'
		         	},
		         	{
                      name:'Ajnala'
		         	},
		         	{
                      name:'Amritsar -I'
		         	},
		         	{
                      name:'Amritsar- II'
		         	},
		         	{
		         		name:'Baba Bakala'
		         	},
		         	{
		         		name:'Baba Bakala'
		         	}
	         	]
	         },
	         {
	         	name:'Tarn Taran',
	         	block:[
		         	{
                      name:'Tarn Taran'
		         	},
		         	{
                      name:'Patti'
		         	},
		         	{
                      name:'Khadur Sahib'
		         	}
	         	]
	         },
	         {
	         	name:'Rupnagar',
	         	block:[
		         	{
                      name:'Rupnagar'
		         	},
		         	{
                      name:'Anandpur Sahib'
		         	},
		         	{
                      name:'Nangal'
		         	},
		         	{
                      name:'Chamkaur Sahib'
		         	}
	         	]
	         },
	         {
	         	name:'Sahibzada Ajit Singh Nagar',
	         	block:[
		         	{
                      name:'Sahibzada Ajit Singh Nagar'
		         	},
		         	{
                      name:'Kharar'
		         	},
		         	{
                      name:'SAS Nagar (Mohali)'
		         	},
		         	{
                      name:'Dera Bassi'
		         	}
	         	]
	         },
	         {
	         	name:'Sangrur',
	         	block:[
		         	{
                      name:'Sangrur'
		         	},
		         	{
                      name:'Malerkotla'
		         	},
		         	{
                      name:'Dhuri'
		         	},
		         	{
                      name:'Lehra'
		         	},
		         	{
                      name:'Moonak'
		         	}
	         	]
	         },
	         {
	         	name:'Barnala',
	         	block:[
		         	{
                      name:'Barnala'
		         	},
		         	{
                      name:'Tapa'
		         	}
	         	]
	         }

	       ]	
		},
		{
         name:'CHANDIGARH',
         dist:[
	         {
	         	name:'Chandigarh',
	         	block:[
		         	{
                      name:'Chandigarh'
		         	}
	         	]
	         },
	       ]
	   },
		{
         name:'UTTARAKHAND',
         dist:[
	         {
	         	name:'Uttarkashi',
	         	block:[
		         	{
                      name:'Uttarkashi'
		         	},
		         	{
                      name:'Puraula'
		         	},
		         	{
                      name:'Mori'
		         	},
		         	{
                      name:'Rajgarhi'
		         	},
		         	{
                      name:'Dunda'
		         	},
		         	{
                      name:'Chiniyalisaur'
		         	},
		         	{
                      name:'Bhatwari'
		         	},
		         	{
                      name:'Bhatwari'
		         	}
	         	]
	         },
	         {
	         	name:'Chamoli',
	         	block:[
		         	{
                      name:'Chamoli'
		         	},
		         	{
                      name:'Joshimath'
		         	},
		         	{
                      name:'Pokhari'
		         	},
		         	{
                      name:'Karnaprayag'
		         	},
		         	{
                      name:'Tharali'
		         	},
		         	{
                      name:'Gairsain'
		         	}
	         	]
	         },
	         {
	         	name:'Rudraprayag',
	         	block:[
		         	{
                      name:'Rudraprayag'
		         	},
		         	{
                      name:'Ukhimath'
		         	},
		         	{
                      name:'Jakholi'
		         	}
	         	  ]
	         },
	         {
	         	name:'Tehri Garhwal',
	         	block:[
		         	{
                      name:'Tehri Garhwal'
		         	},
		         	{
                      name:'Ghansali'
		         	},
		         	{
                      name:'Devprayag'
		         	},
		         	{
                      name:'Pratapnagar'
		         	},
		         	{
                      name:'Jakhani Dhar'
		         	},
		         	{
                      name:'Tehri  '
		         	},
		         	{
                      name:'Dhanaulti'
		         	},
		         	{
                      name:'Narendra Nagar'
		         	}
	         	  ]
	         },
	         {
	         	name:'Dehradun',
	         	block:[
		         	{
                      name:'Dehradun'
		         	},
		         	{
                      name:'Chakrata'
		         	},
		         	{
                      name:'Tyuni'
		         	},
		         	{
                      name:'Kalsi'
		         	},
		         	{
                      name:'Vikas Nagar'
		         	},
		         	{
                      name:'Rishikesh'
		         	}
	         	  ]
	         },
	         {
	         	name:'Garhwal',
	         	block:[
		         	{
                      name:'Garhwal'
		         	},
		         	{
                      name:'Srinagar'
		         	},
		         	{
                      name:'Pauri'
		         	},
		         	{
                      name:'Thailisain'
		         	},
		         	{
                      name:'Dhoomakot'
		         	},
		         	{
                      name:'Lansdowne'
		         	},
		         	{
                      name:'Satpuli'
		         	},
		         	{
                      name:'Chaubatta Khal'
		         	},
		         	{
                      name:'Kotdwara'
		         	},
		         	{
                      name:'Yamkeshwar'
		         	}
	         	  ]
	         },
	         {
	         	name:'Pithoragarh',
	         	block:[
		         	{
                      name:'Pithoragarh'
		         	},
		         	{
                      name:'Munsiari'
		         	},
		         	{
                      name:'Dharchula'
		         	},
		         	{
                      name:'Didihat'
		         	},
		         	{
                      name:'Berinag'
		         	},
		         	{
                      name:'Gangolihat'
		         	}
	         	  ]
	         },
	         {
	         	name:'Bageshwar',
	         	block:[
		         	{
                      name:'Bageshwar'
		         	},
		         	{
                      name:'Kapkot'
		         	},
		         	{
                      name:'Kanda'
		         	},
		         	{
                      name:'Garud'
		         	}
	         	  ]
	         },
	         {
	         	name:'Almora',
	         	block:[
		         	{
                      name:'Almora'
		         	},
		         	{
                      name:'Bhikiasain'
		         	},
		         	{
                      name:'Chaukhutiya'
		         	},
		         	{
                      name:'Sult'
		         	},
		         	{
                      name:'Ranikhet'
		         	},
		         	{
                      name:'Dwarahat'
		         	},
		         	{
                      name:'Someshwar'
		         	},
		         	{
                      name:'Jainti'
		         	},
		         	{
                      name:'Bhanoli'
		         	}
	         	  ]
	         },
	         {
	         	name:'Champawat',
	         	block:[
		         	{
                      name:'Champawat'
		         	},
		         	{
                      name:'Pati'
		         	},
		         	{
                      name:'Lohaghat'
		         	},
		         	{
                      name:'Poornagiri'
		         	}
	         	  ]
	         },
	         {
	         	name:'Nainital',
	         	block:[
		         	{
                      name:'Nainital'
		         	},
		         	{
                      name:'Kosya Kutauli'
		         	},
		         	{
                      name:'Betalghat'
		         	},
		         	{
                      name:'Dhari'
		         	},
		         	{
                      name:'Haldwani'
		         	},
		         	{
                      name:'Ramnagar'
		         	},
		         	{
                      name:'Kaladhungi'
		         	},
		         	{
                      name:'Lalkuan'
		         	}
	         	  ]
	         },
	         {
	         	name:'Udham Singh Nagar',
	         	block:[
		         	{
                      name:'Udham Singh Nagar'
		         	},
		         	{
                      name:'Kashipur'
		         	},
		         	{
                      name:'Jaspur'
		         	},
		         	{
                      name:'Bajpur'
		         	},
		         	{
                      name:'Kichha'
		         	},
		         	{
                      name:'Gadarpur'
		         	},
		         	{
                      name:'Sitarganj'
		         	},
		         	{
                      name:'Khatima'
		         	}
	         	  ]
	         },
	         {
	         	name:'Hardwar',
	         	block:[
		         	{
                      name:'Hardwar'
		         	},
		         	{
                      name:'Roorkee'
		         	},
		         	{
                      name:'Laksar'
		         	}
	         	  ]
	         }
	       ]
	   },
	   {
         name:'HARYANA',
         dist:[
	         {
	         	name:'Panchkula',
	         	block:[
		         	{
                      name:'Panchkula'
		         	},
		         	{
                      name:'Kalka'
		         	}
	         	]
	         },
	         {
	         	name:'Ambala',
	         	block:[
		         	{
                      name:'Naraingarh'
		         	},
		         	{
                      name:'Barara'
		         	}
	         	]
	         },
	         {
	         	name:'Ambala',
	         	block:[
		         	{
                      name:'Naraingarh'
		         	},
		         	{
                      name:'Barara'
		         	}
	         	]
	         },
	          {
	         	name:'Yamunanagar',
	         	block:[
		         	{
                      name:'Naraingarh'
		         	},
		         	{
                      name:'Barara'
		         	}
	         	]
	         },
	      ]
	   } 
	]
}